# MOA LASSO AND PCA ANALYSIS

#### For the mechanism of analysis for a new drug we intend to perform a feature selection to know what features are important for analysis

#### The output consist of about 403 columns that needs to be reduced using principal component analysis and from there we can perform feature selection on the input variables

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import Lasso
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
%matplotlib inline

In [2]:
df = pd.read_csv("~/Desktop/MoaKaggleCompetition/DataSets/train_features.csv")
target = pd.read_csv("~/Desktop/MoaKaggleCompetition/DataSets/train_targets_scored.csv")

In [3]:
df.describe()

,cp_time,g-0,g-1,g-2,g-3,g-4,g-5,g-6,g-7,g-8,...,c-90,c-91,c-92,c-93,c-94,c-95,c-96,c-97,c-98,c-99
count,23814.000000,23814.000000,23814.000000,23814.000000,23814.000000,23814.000000,23814.000000,23814.000000,23814.000000,23814.000000,...,23814.000000,23814.000000,23814.000000,23814.000000,23814.000000,23814.000000,23814.000000,23814.000000,23814.000000,23814.000000
mean,48.020156,0.248366,-0.095684,0.152253,0.081971,0.057347,-0.138836,0.035961,-0.202651,-0.190083,...,-0.469244,-0.461411,-0.513256,-0.500142,-0.507093,-0.353726,-0.463485,-0.378241,-0.470252,-0.301505
std,19.402807,1.393399,0.812363,1.035731,0.950012,1.032091,1.179388,0.882395,1.125494,1.749885,...,2.000488,2.042475,2.001714,2.107105,2.159589,1.629291,2.059725,1.703615,1.834828,1.407918
min,24.000000,-5.513000,-5.737000,-9.104000,-5.998000,-6.369000,-10.000000,-10.000000,-10.000000,-10.000000,...,-10.000000,-10.000000,-10.000000,-10.000000,-10.000000,-10.000000,-10.000000,-10.000000,-10.000000,-10.000000
25%,24.000000,-0.473075,-0.562200,-0.437750,-0.429575,-0.470925,-0.602225,-0.493900,-0.525175,-0.511675,...,-0.566175,-0.565975,-0.589975,-0.568700,-0.563775,-0.567975,-0.552575,-0.561000,-0.592600,-0.562900
50%,48.000000,-0.008850,-0.046600,0.075200,0.008050,-0.026900,-0.015650,-0.000650,-0.017900,0.010000,...,-0.009900,0.003250,-0.009100,-0.013750,-0.003300,-0.010250,-0.001250,-0.006800,0.014000,-0.019500
75%,72.000000,0.525700,0.403075,0.663925,0.463400,0.465375,0.510425,0.528725,0.411900,0.549225,...,0.457750,0.461500,0.445675,0.452900,0.470900,0.444750,0.465225,0.446400,0.461275,0.438650
max,72.000000,10.000000,5.039000,8.257000,10.000000,10.000000,7.282000,7.333000,5.473000,8.887000,...,4.069000,3.960000,3.927000,3.596000,3.747000,2.814000,3.505000,2.924000,3.111000,3.805000

#### PCA on target variables

In [4]:
pca = PCA(n_components=1)
principalComponents = pca.fit_transform(target.drop("sig_id", axis=1))
targetDf = pd.DataFrame(data = principalComponents
             , columns = ['target'])

In [5]:
targetDf.head()

     target
0 -0.043681
1 -0.041774
2 -0.078346
3 -0.041774
4 -0.051955

In [6]:
targetDf = targetDf["target"].apply(lambda x: 0 if x < 0 else 1)

In [7]:
targetDf.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [8]:
len(targetDf[targetDf==0])

22974

In [9]:
len(targetDf[targetDf==1])

840

In [10]:
df.head()

,sig_id,cp_type,cp_time,cp_dose,g-0,g-1,g-2,g-3,g-4,g-5,...,c-90,c-91,c-92,c-93,c-94,c-95,c-96,c-97,c-98,c-99
0,id_000644bb2,trt_cp,24,D1,1.0620,0.5577,-0.2479,-0.6208,-0.1944,-1.0120,...,0.2862,0.2584,0.8076,0.5523,-0.1912,0.6584,-0.3981,0.2139,0.3801,0.4176
1,id_000779bfc,trt_cp,72,D1,0.0743,0.4087,0.2991,0.0604,1.0190,0.5207,...,-0.4265,0.7543,0.4708,0.0230,0.2957,0.4899,0.1522,0.1241,0.6077,0.7371
2,id_000a6266a,trt_cp,48,D1,0.6280,0.5817,1.5540,-0.0764,-0.0323,1.2390,...,-0.7250,-0.6297,0.6103,0.0223,-1.3240,-0.3174,-0.6417,-0.2187,-1.4080,0.6931
3,id_0015fd391,trt_cp,48,D1,-0.5138,-0.2491,-0.2656,0.5288,4.0620,-0.8095,...,-2.0990,-0.6441,-5.6300,-1.3780,-0.8632,-1.2880,-1.6210,-0.8784,-0.3876,-0.8154
4,id_001626bd3,trt_cp,72,D2,-0.3254,-0.4009,0.9700,0.6919,1.4180,-0.8244,...,0.0042,0.0048,0.6670,1.0690,0.5523,-0.3031,0.1094,0.2885,-0.3786,0.7125

In [11]:
df_without_id = df.drop("sig_id", axis=1)

In [12]:
dummy = pd.get_dummies(df_without_id [["cp_type","cp_dose"]])

In [13]:
df_without_id = df_without_id.merge(dummy, left_index=True, right_index = True)

In [14]:
df_without_id = df_without_id.drop(columns=["cp_type","cp_dose"])

In [15]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    penalty='l1',
    solver='saga')

model.fit(df_without_id, targetDf.values)

/Applications/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/sag.py:334: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l1', random_state=None, solver='saga',
          tol=0.0001, verbose=0, warm_start=False)

In [16]:
res =pd.DataFrame(zip(df_without_id.columns, np.transpose(model.coef_[0])), columns=['features', 'coef'])

In [17]:
fil_res = res[res["coef"] != 0]

In [18]:
len(fil_res)

866

In [55]:
fil_res.sort_values(by=['coef'], ascending=False, inplace= True)

/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [19]:
fil_res.head(50)

   features      coef
0   cp_time -0.076849
1       g-0 -0.036557
2       g-1  0.051171
3       g-2 -0.122992
4       g-3  0.010299
5       g-4 -0.000906
6       g-5  0.031905
7       g-6 -0.012101
8       g-7 -0.014604
9       g-8 -0.028649
10      g-9 -0.071320
11     g-10 -0.044578
12     g-11  0.096109
13     g-12 -0.098626
14     g-13  0.024850
15     g-14  0.014951
16     g-15  0.021015
17     g-16 -0.008490
18     g-17  0.011897
19     g-18 -0.048087
20     g-19  0.022447
21     g-20 -0.049317
23     g-22  0.003888
24     g-23  0.026571
25     g-24 -0.044427
26     g-25 -0.039561
27     g-26 -0.039600
28     g-27  0.026971
29     g-28  0.082103
30     g-29 -0.045544
31     g-30 -0.004160
32     g-31  0.030601
33     g-32  0.009569
34     g-33  0.035211
35     g-34 -0.012606
36     g-35 -0.055254
37     g-36  0.015717
38     g-37  0.064811
39     g-38 -0.107277
40     g-39 -0.021636
41     g-40 -0.045700
42     g-41 -0.009189
43     g-42  0.048715
44     g-43 -0.012252
45     g-44 -0.058264
46     g-45  0.061468
47     g-46  0.042581
48     g-47  0.053240
49     g-48  0.003948
50     g-49  0.052481